/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uam.view;

import cr.ac.uam.bl.Clientes;
import cr.ac.uam.domain.Cliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crisrc012
 */
public class frmClientes extends javax.swing.JFrame {

    public Cliente clienteActual = null;
    private Clientes clientes = null;

    /**
     * Creates new form frmClientes
     */
    public frmClientes() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTableClientes.getModel();
        clientes = new Clientes();
        for (Cliente cliente : clientes.getClientes()) {
            model.addRow(new Object[]{cliente.getCedula(),
                cliente.getNombre(),
                cliente.getApellido(),
                cliente.getEmail()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jLabel1.setText("Lista de clientes");

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTableClientes.getSelectedRowCount() != 1) {
            if (jTableClientes.getSelectedRowCount() < 0) {
                JOptionPane.showMessageDialog(null, "Por favor seleccionar al menos un cliente", "Atención", JOptionPane.ERROR_MESSAGE);
            }
            if (jTableClientes.getSelectedRowCount() > 1) {
                JOptionPane.showMessageDialog(null, "Por favor seleccionar al unicamente un cliente", "Atención", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            clienteActual = new Cliente();
            this.clienteActual.setCedula(String.valueOf(jTableClientes.getModel().getValueAt(jTableClientes.getSelectedRow(), 0)));
            this.clienteActual.setNombre(String.valueOf(jTableClientes.getModel().getValueAt(jTableClientes.getSelectedRow(), 1)));
            this.clienteActual.setApellido(String.valueOf(jTableClientes.getModel().getValueAt(jTableClientes.getSelectedRow(), 2)));
            this.clienteActual.setEmail(String.valueOf(jTableClientes.getModel().getValueAt(jTableClientes.getSelectedRow(), 3)));
            frmFactura.setclienteActual(clienteActual);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables
}
