/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uam.view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import cr.ac.uam.bl.Facturacion;
import cr.ac.uam.domain.Factura;
import cr.ac.uam.domain.Producto;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//http://www.vogella.com/tutorials/JavaPDF/article.html

/**
 *
 * @author crisrc012
 */
public class frmFacturas extends javax.swing.JFrame {

    public Facturacion facturas = null;

    /**
     * Creates new form frmInventario
     */
    public frmFacturas() {
        initComponents();
        facturas = new Facturacion();
        updateJTable();
    }

    public Facturacion getFacturas() {
        return facturas;
    }
    
    public void addFactura(Factura factura){
        this.facturas.getFacturas().add(factura);
        updateJTable();
    }
    
    private void updateJTable() {
        DefaultTableModel model = (DefaultTableModel) jTableFacturas.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Factura factura : this.facturas.getFacturas()) {
            model.addRow(new Object[]{
                factura.getId(),
                new SimpleDateFormat("dd-MM-yyyy").format(factura.getFecha()),
                factura.getCliente().getNombre() + " " + factura.getCliente().getApellido()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jLblFacturas = new javax.swing.JLabel();
        jBtnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fecha", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFacturas);

        jLblFacturas.setText("Facturas");

        jBtnImprimir.setText("Imprimir");
        jBtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblFacturas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnImprimir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblFacturas)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnImprimir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Factura getFactura(int id) {
        for (Factura f : facturas.getFacturas()) {
            if (f.getId() == id) {
                return f;
            }
        }
        return null;
    }

    private void jBtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImprimirActionPerformed
        if (jTableFacturas.getSelectedRowCount() != 1) {
            if (jTableFacturas.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Por favor seleccionar al menos una factura",
                        "Atención",
                        JOptionPane.ERROR_MESSAGE);
            }
            if (jTableFacturas.getSelectedRowCount() > 1) {
                JOptionPane.showMessageDialog(this,
                        "Por favor seleccionar unicamente una factura",
                        "Atención",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Factura factura = getFactura((int) jTableFacturas.getValueAt(
                    jTableFacturas.getSelectedRow(), 0));
            try {
                imprimirFactura(factura);
            } catch (IOException ex) {
                Logger.getLogger(frmFacturas.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jBtnImprimirActionPerformed

    private void imprimirFactura(Factura factura) throws IOException {
        String FILE = "C:/Users/crobles/Desktop/Invoice.pdf";
        Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
                Font.BOLD);
        Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
                Font.BOLD);
        Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
                Font.BOLD);
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            Paragraph header = new Paragraph();
            header.add(new Paragraph("Factura # " + factura.getId(), catFont));
            header.add(new Paragraph(
                    "\n\nFecha: " + new SimpleDateFormat("dd-MM-yyyy").format(factura.getFecha()),
                    smallBold));
            header.add(new Paragraph(
                    "\nCédula: " + factura.getCliente().getCedula(), smallBold));
            header.add(new Paragraph(
                    "Cliente: "
                    + factura.getCliente().getNombre() + " "
                    + factura.getCliente().getApellido(), smallBold));
            document.add(header);

            //Tabla
            Paragraph paragraphTable = new Paragraph("\nProductos:", subFont);
            PdfPTable table = new PdfPTable(4);
            PdfPCell c1 = new PdfPCell(new Phrase("Código"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("Descripción"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("Cantidad"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("Precio Unitario"));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c1);
            table.setHeaderRows(1);
            // Datos Codigo, Descripción, Cantidad, Precio
            Double subtotal = 0.0;
            for (Producto p : factura.getProductos()) {
                table.addCell(String.valueOf(p.getId()));
                table.addCell(p.getDescripcion());
                table.addCell(String.valueOf(p.getCantidad()));
                table.addCell(String.valueOf(p.getValor()));
                subtotal += p.getCantidad() * p.getValor();
            }
            paragraphTable.add(table);
            document.add(paragraphTable);

            //Pie de página
            Double impuesto = subtotal * 0.13;
            Double total = subtotal + impuesto;
            Paragraph footer = new Paragraph();
            footer.add(new Paragraph("\n\nSubtotal: " + subtotal));
            footer.add(new Paragraph("Impuesto: " + impuesto));
            footer.add(new Paragraph("Total: " + total));
            document.add(footer);
            document.close();
            Desktop.getDesktop().open(new File(FILE));
        } catch (DocumentException | FileNotFoundException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnImprimir;
    private javax.swing.JLabel jLblFacturas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFacturas;
    // End of variables declaration//GEN-END:variables
}
