/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.uam.view;

import cr.ac.uam.bl.Facturacion;
import cr.ac.uam.domain.Factura;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crisrc012
 */
public class frmFacturas extends javax.swing.JFrame {

    public Facturacion facturas = null;

    /**
     * Creates new form frmInventario
     */
    public frmFacturas() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTableFacturas.getModel();
        facturas = new Facturacion();
        for (Factura factura : facturas.getFacturas()) {
            model.addRow(new Object[]{
                factura.getId(),
                new SimpleDateFormat("dd-MM-yyyy").format(factura.getFecha()),
                factura.getCliente().getNombre() + " " + factura.getCliente().getApellido()});
        }
    }

    public Facturacion getFacturas() {
        return facturas;
    }

    public void setFacturas(Facturacion facturas) {
        this.facturas = facturas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jLblFacturas = new javax.swing.JLabel();
        jBtnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fecha", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFacturas);

        jLblFacturas.setText("Facturas");

        jBtnImprimir.setText("Imprimir");
        jBtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblFacturas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnImprimir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblFacturas)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnImprimir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Factura getFactura(int id) {
        for (Factura f : facturas.getFacturas()) {
            if (f.getId() == id) {
                return f;
            }
        }
        return null;
    }

    private void jBtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnImprimirActionPerformed
        if (jTableFacturas.getSelectedRowCount() != 1) {
            if (jTableFacturas.getSelectedRowCount() <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Por favor seleccionar al menos una factura",
                        "Atención",
                        JOptionPane.ERROR_MESSAGE);
            }
            if (jTableFacturas.getSelectedRowCount() > 1) {
                JOptionPane.showMessageDialog(this,
                        "Por favor seleccionar unicamente una factura",
                        "Atención",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Factura factura = getFactura((int) jTableFacturas.getValueAt(
                    jTableFacturas.getSelectedRow(), 0));

            this.dispose();
        }
    }//GEN-LAST:event_jBtnImprimirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnImprimir;
    private javax.swing.JLabel jLblFacturas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFacturas;
    // End of variables declaration//GEN-END:variables
}
